Workflow updates
RockefellerArchiveCenter/cartographer_backend pull request #195
Opened 2024-09-09 19:11 UTC by p-galligan

Migrates from Travis to GitHub Actions.

2024-09-09 23:30 UTC, helrond reviewed
Branch protection rules for `development` need to be updated.

2024-09-10 00:00 UTC, p-galligan commented
> Branch protection rules for `development` need to be updated.

Good catch, thanks!

2024-09-10 13:21 UTC, helrond approved these changes

2024-09-10 13:23 UTC, HaSistrunk approved these changes

2024-09-10 13:36 UTC, HaSistrunk requested changes
Should cleanup travis remnants by removing the travis build status from readme

2024-09-11 17:46 UTC, HaSistrunk approved these changes

2024-09-11 17:50 UTC, merged